image: alpine:latest

pages:
  stage: deploy
  before_script:
  - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan $EC2_IPADDRESS >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
  - ssh $SSH_USER@$EC2_IPADDRESS " cd /tmp/ && rm -rf toneita-admin-panel/ && sudo git clone -b development https://$CI_DEPLOY_USER:$CI_DEPLOY_PASSWORD@$CI_REGISTRY && sudo cp -r -f /tmp/toneita-admin-panel/* /root/nginxproxy/toneitaadmindev/ && cd /root/nginxproxy/toneitaadmindev/ && sudo docker-compose down && sudo docker-compose up -d --build --force-recreate  &&  rm -r /tmp/toneita-admin-panel && exit "
  only:
  - development
